In [45]:
import numpy as np
import matplotlib.pyplot as plt
import math
from functools import cmp_to_key

In [46]:
INPUT_SIZE = 3
TRAINING_SIZE = 10000

In [47]:
class WeightedLocalRegression:

    def __init__(self, instances, targets):
        self.__LR = 0.0003

        self.__k = 8
        self.__instances = []
        self.__targets = []
        self.__original_instances = instances
        self.__original_targets = targets

    def __apply(self, instance):
        return self.__weights[0] + sum([i * j for i, j in zip(instance, self.__weights[1:])])
    
    def __distance(self, instance1, instance2):
        #print(str(instance1) + " " + str(instance2) + " " + str(sum([(i - j) * (i - j) for i, j in zip(instance1, instance2)])))
        return math.sqrt(sum([(i - j) * (i - j) for i, j in zip(instance1, instance2)]))

    def __kernel(self, instance1, instance2):
        return 1 / self.__distance(instance1, instance2)

    def __create_training(self, instance):
        self.__instances = []
        self.__targets = []

        for training_instance, training_target in zip(self.__original_instances, self.__original_targets):
            kernel_value = int(self.__kernel(instance, training_instance))
            self.__instances.extend([training_instance] * kernel_value)
            self.__targets.extend([training_target] * kernel_value)
        print(len(self.__instances))


    def query(self, instance):
        self.__weights = np.random.random_sample((1, INPUT_SIZE))[0]

        self.__create_training(instance)
        self.__update_weights()
        
        print(self.__weights)

        return self.__apply(instance)
    
    def __closest(self, instance):
        return sorted(self.__instances, key = cmp_to_key(lambda x, y : self.__distance(x, instance) < self.__distance(y, instance)))[:self.__k]

    def __weight_delta(self, j):
        return self.__LR * sum([(result - self.__apply(x)) * x[j] for x, result in zip(self.__instances, self.__targets)])
    
    def __update_weights(self):
        for j in range(len(self.__weights) - 1):
           self.__weights[j + 1] = self.__weights[j + 1] + self.__weight_delta(j)


In [48]:
def target_function(x):
    return x[0] / 3 - 15 * x[1] / 15 + 17/15 * x[2]

training_instances = np.random.random_sample((TRAINING_SIZE, INPUT_SIZE))
training_targets = [target_function(x) for x in training_instances]

learner = WeightedLocalRegression(training_instances, training_targets)

x = np.random.random_sample((15, INPUT_SIZE))
#x = [[0.6, 0.978, 0.013], [0.05, 0.7, 0.005], [0.4, 1.005, 1.2], [0.004, 0.17, 0.82], [0.23, 0.01, 0.56]]

for instance in x:
    print(str(learner.query(instance)) + " " + str(target_function(instance)))


17251
[ 0.8220665  -1.94946067  0.13719825]
0.013716497548582951 -0.09418051768890909
15260
[ 0.28948276 -1.20932848  0.79222799]
-0.40656843612386373 0.5190525791015814
16474
[ 0.21140171 -0.71637315  0.16476325]
-0.02458185380673167 0.0539175530581405
13746
[ 0.88749129 -2.40252827  1.33173742]
-0.3185654769243278 0.6976396134938507
17081
[ 0.25559672 -0.32292391  0.04733006]
0.08353983641489968 0.4464182483717717
15020
[ 0.91568543 -2.96953601 -0.39641029]
-0.44716160158094853 -0.4060436902428494
9366
[0.20064676 0.38477383 0.03800141]
0.24363486435888418 1.0253393080505384
17242
[ 0.39784861 -1.13869151  0.90981717]
0.10778214333539082 0.4990269075723022
12654
[ 0.53056696 -2.78172687  2.32486994]
0.25705123343607605 0.11066664213421817
15501
[ 0.84400432 -1.26867896 -0.19156288]
0.3599309313520065 0.7116931297816693
14873
[ 0.32094898 -0.7755473   0.52180458]
-0.009197532073213388 0.7835001680186308
14556
[ 0.81220476 -1.86956839  0.27196099]
0.23782454793323016 0.7177143308155638